spring.application.name=currency-exchange

server.port = 8000
eureka.client.service-url.defaultZone = http://localhost:8761/eureka

#Konfiguracija RETRY mehanizma
#Vreme cekanja izmedju ponovnih zahteva
resilience4j.retry.instances.default.wait-duration=2s
#Broj zahteva koje primenjuje retry mehanizam
resilience4j.retry.instances.default.max-attempts=8